### DISCUSSION TITLE
A hello world campaign as starting point

### DISCUSSION THREAD

**Discussion by lukaszgemborowski** [Khopa/dcs_liberation#1799] [Q&A] [answered]
... or a good guide of sorts. I am trying to create simple campaign but I'm failing. My idea was to start with two airbases and couple of squadrons (in Marianas) but it seems there's not much docs around. Yes, there's general [wiki](https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-Campaigns) about that, there are already-done campaigns that I can base on but they're not really helpful. I've marked two airbases for reds and blues, I've added sample squads of F-16's and 18's:

```
squadrons:
  # Andersen AFB Blue
  6:
    - primary: BARCAP
      aircraft: F-16CM Fighting Falcon (Block 50)
    - primary: BARCAP
      aircraft: F/A-18C Hornet (Lot 20)
  # Saipan RED
  2:
    - primary: BARCAP
      secondary: air-to-air
```

but instead I'm getting a LOT of errors in the log and only two F-15's squads in the campaign. The minimal example will be really helpful I think.
